import { type ReactNode } from "react";
import Head from "next/head";
import Navbar from "./Navbar";

const Layout = ({ children }: { children: ReactNode }) => {
  return (
    <div className="min-h-screen">
      <Head>
        <title>Generator Ikon</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/logo1.jpg" />
      </Head>
      <header className="min-w-[400px] bg-neutral-900/50 shadow-md shadow-gray-500">
        <Navbar />
      </header>
      <main className=" mx-auto  mt-20 w-11/12 ">{children}</main>
    </div>
  );
};

export default Layout;
